import re

'''
Takes a stream of source chunks (with citation blocks), and prepares the target stream (with citation blocks) as well as the list of citations.

A source stream consists of several chunks. For each new chunk, call add_text method. 
Each source chunk can contain zero or more citation blocks (including citation literal)

A citation block consists of two parts; citation tag and citation ids. E.g. for citation block [[cite]][1,2,..] 
    - [[cite]] is the citation tag
    - 1,2.. are the citation ids

If the pattern [[cite]] needs to be part of the actual data, a single backslash (\\) can be used to escape it. E.g
    - [[cite]] is citation tag
    - \\[[cite]] is literal text [[cite]]
    - \\\\[[cite]] is literal text \\[cite]

No other  backslashes are treated as escape character.

The target stream is essentially generated by removing citation blocks from the source stream. Each source chunk consists of one or more chunk spans, 
where span is the text in-between citation blocks. The target stream consists of consecutive blocks of text, where each block of text has associated
citations. The target stream is generated incrementally from the source chunks. Note that it is possible for citation block to be divided between two
adjacent source chunks. This means that identification of citation block needs to account for partial pattern matching across adjacent chunks.

Also, a target block can span across one or more source chunks. When a citation block is identified, we can close the current target block and generate
a list of citations for that target block and start a new target block.

Onec all the source chunks are processed (by calling add_chunk), we must call end_stream() to finish processing any remaining text (partially matching 
citation tag pattern)

'''

class CitationProcessor:

    def __init__(self):

        self.target_text = '' #represents accumulated target text across turns so far after extracting citations 
        self.curr_target_block_start_index = 0 #represents start index of the curr block
        self.src_leftover_text = '' #represents src text leftover from the previous turn to be combined with the src text in the next turn 
        self.all_citations = [] #represents all the citations collected so far
        
      
    def add_chunk(self, src_chunk: str):

        if not src_chunk:
            return '', []

        # text to be processed in this turn 
        src_text = self.src_leftover_text + src_chunk

        extracted_text = ''
        citations = []

        curr_span_text = ''
        curr_span_start_index = 0
        
        #process each citation tag occurrence in the raw text
        for tag_matchobj in re.finditer(r'\[\[cite\]\]', src_text):

            cite_tag_start_index = tag_matchobj.span()[0]
            cite_tag = tag_matchobj.group()
            cite_tag_len = len(cite_tag)
            
            # if this instance of [[cite]] occurs as literal (that is with a leading backslash), 
            # add it to text after removing the backslash and continue
            if cite_tag_start_index > 0 and src_text[cite_tag_start_index - 1] == '\\':

                curr_span_text += src_text[curr_span_start_index : cite_tag_start_index - 1] #add text from curr span before backslash
                curr_span_text += cite_tag #add the literal to extracted text
                curr_span_start_index = cite_tag_start_index + cite_tag_len #continue the span after the escaped citation block
                
                continue

            #extract citation source ids
            
            id_start = tag_matchobj.span()[1] #start index of the ids [1,2..]
            id_match_obj = re.search(r'\[(([\d\s,])+)\]' , src_text[id_start:]) #find all the source_ids

            source_ids_str = id_match_obj.group(1) if id_match_obj else ''
            source_ids = [int(id_str) for id_str in source_ids_str.split(',') if len(id_str) > 0]

            if len(source_ids) > 0:

                cite_block_len = cite_tag_len + len(id_match_obj.group())

                #add text to current span (without the citation block)
                curr_span_text += src_text[curr_span_start_index : cite_tag_start_index]
            
                #add current span to extracted_text
                extracted_text += curr_span_text

                #compute current blocks end index correctly (wrt the target stream)
                curr_block_end_index = self.curr_target_block_start_index + len(curr_span_text)

                #if this block started before this chunk, also add the length of block before this chunk
                if self.curr_target_block_start_index < len(self.target_text):
                    block_len_before_curr_chunk = len(self.target_text) - self.curr_target_block_start_index
                    curr_block_end_index += block_len_before_curr_chunk

                #add citations
                citation_obj = (
                    self.curr_target_block_start_index, 
                    curr_block_end_index,
                    source_ids.copy()
                )

                #add the citation block
                citations.append(citation_obj)
                
                #start a new target block
                self.curr_target_block_start_index = curr_block_end_index

                #start a new span
                curr_span_text = ''
                curr_span_start_index = cite_tag_start_index + cite_block_len

            else:
                pass
                #corner case.. citation tag found but citation ids missing. Treat as regular text.
                #just skip. The next iteration or the logic to process remaining text will take care of this.
            

        #process the remaining raw text (which doesn't have complete citations but may still have partial citations)
        #and add to current span part of it which doesn't match the partial cite block pattern
        if curr_span_start_index < len(src_text): 

            rem_text = src_text[curr_span_start_index: ]
            end_index = len(rem_text)
            partial_matched = False
            
            for pattern in [r'\[[cite]]', r'[[cite]]']:
                for i in range(1, len(pattern))[::-1]:
                    partial_pattern = pattern[:i]
                    if rem_text.endswith(partial_pattern):
                        partial_matched = True
                        end_index = len(rem_text) - len(partial_pattern)
                        break
                if partial_matched: 
                    break

            curr_span_text += rem_text[:end_index]
        
        extracted_text += curr_span_text
        self.src_leftover_text = rem_text[end_index:]

        #update global state
        self.target_text += extracted_text
        #self.curr_target_block_start_index = len(self.target_text) #intermediate update to current target length since the target block may cross the chunk boundary

        self.all_citations.extend(list(citations))
    
        return extracted_text, citations

    def end_src_stream(self):
        self.target_text += self.src_leftover_text
        

        
    