kafka:
  download_requested_topic: 'download.requested'
  document_fetched_topic: 'document.fetched'

qdrant:
  collection: 'hybrid_collection2'
  fast_embedding_model: 'BAAI/bge-small-en-v1.5'

staging:
  incoming_dir_rel_path: 'staging/incoming'
  fetched_dir_rel_path: 'staging/fetched'

filewatcher:
  stable_checks: 3
  check_interval: 1.0
  initial_delay: 1.0
  max_workers: 4

downloader:
  consumer_group: 'downloader_consumer_group'
  
ingestion:
  consumer_group: 'ingestion_consumer_group'

